# 파일 경로
path:
    train_path: ./dataset/train/train.csv        # train 데이터셋 위치
    valid_path: ./dataset/train/valid.csv        # valid.csv는 베이스라인에는 없는 파일(평가 데이터셋)
    output_dir: ./results                        # output directory
    logging_dir: ./logs                          # directory for storing logs
    MODEL_PATH : ./best_model

    test_path : ./dataset/test/test_data.csv       # test_data.csv 위치
    submission_path: ./prediction/                 # submission.csv 위치
    difference_path: ./prediction/                 # difference.csv 위치
      
    dict_label_to_num: ./code/dict_label_to_num.pkl        # label_to_num 피클파일 위치
    dict_num_to_label: ./code/dict_num_to_label.pkl        # num_to_label 피클파일 위치
      
# 파라미터
params:
    MODEL_NAME: klue/bert-base
        
    save_total_limit: 5                           # number of total save model.
    save_steps: 500                               # model saving step.
    num_train_epochs: 10                          # total number of training epochs
    learning_rate: .00005                         # learning_rate
    per_device_train_batch_size: 32               # batch size per device during training
    per_device_eval_batch_size: 32                # batch size for evaluation
    warmup_steps: 500                             # number of warmup steps for learning rate scheduler
    weight_decay: .01                             # strength of weight decay
        
    logging_steps: 100                            # log saving step.

    evaluation_strategy: steps                    # evaluation strategy to adopt during training
                                                  # `no`: No evaluation during training.
                                                  # `steps`: Evaluate every `eval_steps`.
                                                  # `epoch`: Evaluate every end of epoch
        
    eval_steps: 500                               # evaluation step.
    load_best_model_at_end: true